[project]
name = "agent-tutorial"
version = "0.1.0"
description = "This is a tutorial for ADK on GCP"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=3.4.3",
    "fastmcp>=2.3.5",
    "google-adk>=1.1.0",
    "google-genai>=1.13.0",
    "pydotenv>=0.0.7",
]
